<?php
/**
 * Created by PhpStorm.
 * User: Aad Pouw
 * Date: 20-8-2022
 * Time: 22:48
 */
namespace TP_Core\Libs\SiteMaps;
use TP_Core\Traits\I10n\_I10n_02;
use TP_Core\Traits\Templates\_general_template_08;
if(ABSPATH){
    class TP_Sitemaps_Stylesheet extends Sitemaps_Base {
        use _general_template_08,_I10n_02;
        public function render_stylesheet( $type ):void{
            header( 'Content-type: application/xml; charset=UTF-8' );
            if ( 'sitemap' === $type){$this->_e($this->get_sitemap_stylesheet());}
            if ( 'index' === $type ){$this->_e($this->get_sitemap_index_stylesheet());}
            exit;
        }//23
        public function get_sitemap_stylesheet(){
            $css         = $this->get_stylesheet_css();
            $title       = $this->_esc_xml( $this->__( 'XML Sitemap' ) );
            $description = $this->_esc_xml( $this->__( 'This XML Sitemap is generated by TailoredPress to make your content more visible for search engines.' ) );
            $learn_more  = sprintf("<a href='%s'>%s</a>",$this->_esc_url( $this->__( 'https://www.sitemaps.org/' ) ),
                $this->_esc_xml( $this->__( 'Learn more about XML sitemaps.' ) ));
            $text = sprintf($this->_esc_xml( $this->__( 'Number of URLs in this XML Sitemap: %s.' ) ),
                "<xsl:value-of select='count(sitemap:urlset/sitemap:url)' />");/* translators: %s: Number of URLs. */
            $lang       = $this->_get_language_attributes( 'html' );
            $url        = $this->_esc_xml( $this->__( 'URL' ) );
            $lastmod    = $this->_esc_xml( $this->__( 'Last Modified' ) );
            $changefreq = $this->_esc_xml( $this->__( 'Change Frequency' ) );
            $priority   = $this->_esc_xml( $this->__( 'Priority' ) );
            $xsl_content = static function()use($lang,$title,$css,$description,$learn_more,$text,$url,$lastmod,$changefreq,$priority){
                $xml = "<?xml version='1.0' encoding='UTF-8'?>";
                $xml .="<xsl:stylesheet version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform' exclude-result-prefixes='sitemap' />";// xmlns:sitemap='http://www.sitemaps.org/schemas/sitemap/0.9'
                $xml .="<xsl:output method='html' encoding='UTF-8' indent='yes' />";
                $xml .="<xsl:variable name='has-lastmod' select='count( /sitemap:urlset/sitemap:url/sitemap:lastmod )' />";
                $xml .="<xsl:variable name='has-changefreq' select='count( /sitemap:urlset/sitemap:url/sitemap:changefreq )' />";
                $xml .="<xsl:variable name='has-priority' select='count( /sitemap:urlset/sitemap:url/sitemap:priority )' />";
                $xml .="<xsl:template match='/'>";
                $xml .="<html {$lang}><head><title>{$title}</title><style>{$css}</style></head><body>";
                $xml .="<div id='sitemap'>";
                $xml .="<div id='sitemap__header'><h1>{$title}</h1><p>{$description}</p><p>{$learn_more}</p></div>";
                $xml .="<div id='sitemap__content'><p class=\"text\">{$text}</p>";
                $xml .="<table id='sitemap__table'><thead><tr><th class='loc'>{$url}</th>";
                $xml .="<xsl:if test='\$has-lastmod'><th class='last-mod'>{$lastmod}</th></xsl:if>";
                $xml .="<xsl:if test='\$has-changefreq'><th class='change-freq'>{$changefreq}</th></xsl:if>";
                $xml .="<xsl:if test='\$has-priority'><th class='priority'>{$priority}</th></xsl:if>";
                $xml .="</tr></thead><tbody><xsl:for-each select='sitemap:urlset/sitemap:url'><tr>";
                $xml .="<td class='loc'><a href='{sitemap:loc}'><xsl:value-of select='sitemap:loc' /></a></td>";
                $xml .="<xsl:if test='\$has-lastmod'><td class='last-mod'><xsl:value-of select='sitemap:lastmod' /></td></xsl:if>";
                $xml .="<xsl:if test='\$has-changefreq'><td class='change-freq'><xsl:value-of select='sitemap:changefreq' /></td></xsl:if>";
                $xml .="<xsl:if test='\$has-priority'><xsl:value-of select='sitemap:priority' /></xsl:if>";
                $xml .="</tr></xsl:for-each></tbody></table>";//#sitemap__table
                $xml .="</div></div>";//#sitemap__content,//#sitemap
                $xml .="</body></html></xsl:template></xsl:stylesheet>";
                echo $xml;
            };
            return $this->_apply_filters( 'tp_sitemaps_stylesheet_content', $xsl_content );
        }//44
        public function get_sitemap_index_stylesheet(){
            $css         = $this->get_stylesheet_css();
            $title       = $this->_esc_xml( $this->__( 'XML Sitemap' ) );
            $description = $this->_esc_xml( $this->__( 'This XML Sitemap is generated by TailoredPress to make your content more visible for search engines.' ) );
            $learn_more  = sprintf("<a href='%s'>%s</a>",$this->_esc_url( $this->__( 'https://www.sitemaps.org/' ) ),
                $this->_esc_xml( $this->__( 'Learn more about XML sitemaps.' ) ));
            $text = sprintf($this->_esc_xml( $this->__( 'Number of URLs in this XML Sitemap: %s.' ) ),
                "<xsl:value-of select='count(sitemap:sitemapindex/sitemap:sitemap)' />");
            $lang       = $this->_get_language_attributes( 'html' );
            $url        = $this->_esc_xml( $this->__( 'URL' ) );
            $lastmod    = $this->_esc_xml( $this->__( 'Last Modified' ) );
            $xsl_content = static function()use($lang,$title,$css,$description,$learn_more,$text,$url,$lastmod){
                $xml = "<?xml version='1.0' encoding='UTF-8'?>";
                $xml .="<xsl:stylesheet version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform' exclude-result-prefixes='sitemap' />";// xmlns:sitemap='http://www.sitemaps.org/schemas/sitemap/0.9'
                $xml .="<xsl:output method='html' encoding='UTF-8' indent='yes' />";
                $xml .="<xsl:variable name='has-lastmod' select='count( /sitemap:urlset/sitemap:url/sitemap:lastmod )' />";
                $xml .="<xsl:template match='/'>";
                $xml .="<html {$lang}><head><title>{$title}</title><style>{$css}</style></head><body>";
                $xml .="<div id='sitemap'>";
                $xml .="<div id='sitemap__header'><h1>{$title}</h1><p>{$description}</p><p>{$learn_more}</p></div>";
                $xml .="<div id='sitemap__content'><p class=\"text\">{$text}</p>";
                $xml .="<table id='sitemap__table'><thead><tr><th class='loc'>{$url}</th>";
                $xml .="<xsl:if test='\$has-lastmod'><th class=last-mod>{$lastmod}</th></xsl:if>";
                $xml .="</tr></thead><tbody><xsl:for-each select='sitemap:sitemapindex/sitemap:sitemap'><tr>";
                $xml .="<td class=\"loc\"><a href='{sitemap:loc}'><xsl:value-of select='sitemap:loc' /></a></td>";
                $xml .="<xsl:if test='\$has-lastmod'><td class='last-mod'><xsl:value-of select='sitemap:lastmod' /></td></xsl:if>";
                $xml .="</tr></xsl:for-each></tbody></table>";//#sitemap__table
                $xml .="</div></div>";//#sitemap__content,//#sitemap
                $xml .="</body></html></xsl:template></xsl:stylesheet>";
                echo $xml;
            };
            return $this->_apply_filters( 'tp_sitemaps_stylesheet_index_content', $xsl_content );
        }//158
        public function get_stylesheet_css(){
            $text_align = $this->_is_rtl() ? 'right' : 'left';
            $css = static function()use($text_align){
                $xml_css = "body {font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif;color: #444;}";
                $xml_css .= "#sitemap {max-width: 980px;margin: 0 auto;}";
                $xml_css .= "#sitemap__table {width: 100%;border: solid 1px #ccc;border-collapse: collapse;}";
                $xml_css .= "#sitemap__table tr td.loc {direction: ltr;}";
                $xml_css .= "#sitemap__table tr th {text-align: {$text_align};}";
                $xml_css .= "#sitemap__table tr td,#sitemap__table tr th{padding: 10px;}";
                $xml_css .= "#sitemap__table tr:nth-child(odd) td {background-color: #eee;}";
                $xml_css .= "a:hover{text-decoration: none;}";
                $xml_css .= ".last-mod{}";//todo give it a meaning or remove it
                echo $xml_css;
            };
            return $this->_apply_filters( 'tp_sitemaps_stylesheet_css', $css );
        }//258
    }
}else{die;}